export const LIST_DOCS_REQUEST = "LIST_DOCS_REQUEST";
export const LIST_DOCS_SUCCESS = "LIST_DOCS_SUCCESS";
export const LIST_DOCS_FAIL = "LIST_DOCS_FAIL";

export const LIST_JOBS_REQUEST = "LIST_JOBS_REQUEST";
export const LIST_JOBS_SUCCESS = "LIST_JOBS_SUCCESS";
export const LIST_JOBS_FAIL = "LIST_JOBS_FAIL";

export const LIST_SKILLS_REQUEST = "LIST_SKILLS_REQUEST";
export const LIST_SKILLS_SUCCESS = "LIST_SKILLS_SUCCESS";
export const LIST_SKILLS_FAIL = "LIST_SKILLS_FAIL";

export const LIST_EDUCATION_REQUEST = "LIST_EDUCATION_REQUEST";
export const LIST_EDUCATION_SUCCESS = "LIST_EDUCATION_SUCCESS";
export const LIST_EDUCATION_FAIL = "LIST_EDUCATION_FAIL";

export const LIST_LINKS_REQUEST = "LIST_LINKS_REQUEST";
export const LIST_LINKS_SUCCESS = "LIST_LINKS_SUCCESS";
export const LIST_LINKS_FAIL = "LIST_LINKS_FAIL";

export const DOC_REQUEST = "DOC_REQUEST";
export const DOC_SUCCESS = "DOC_SUCCESS";
export const DOC_FAIL = "DOC_FAIL";
